### ISSUE TITLE
Help to setup

### ISSUE THREAD

**Issue by Pratham2137** [bipinkrish/file-converter-telegram-bot#11]
Hello Sir, 
My self Pratham, I want to study your bot but i am not able to install the bot in my machine 
can you please provide a proper procedure to install the bot.
It is showing me the connection error
File "C:\Users\prath\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 547, in send       
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by bipinkrish** [comment]
now Readme has help block.

```
File "C:\Users\prath\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 547, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

maybe your Token is using by another instance of the bot, make sure to run it only one time
