### ISSUE TITLE
no audio for video 

### ISSUE THREAD

**Issue by satyamisme** [bipinkrish/file-converter-telegram-bot#7]
[mjpeg @ 0x55f7d2ac5100] unable to decode APP fields: Invalid data found when processing input
    Last message repeated 9 times
[mjpeg @ 0x55f7d2ac5100] No JPEG data found in image
[matroska,webm @ 0x55f7d2a9e540] decoding for stream 10 failed
[matroska,webm @ 0x55f7d2a9e540] Could not find codec parameters for stream 10 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from '/usr/src/app/downloads/www_HTPMovies_art_Dongalunnaru_Jagratha_2022_1080p_NF_WEB_DL_x264.mkv':
  Metadata:
    title           : www.HTPMovies.art - Dongalunnaru Jagratha (2022) 1080p NF WEB-DL x264 [Telugu (DD+ 5.1 - 192Kbps & AAC 2.0)] MSub
    encoder         : libebml v1.4.2 + libmatroska v1.6.3
    creation_time   : 2022-10-06T19:18:24.000000Z
  Duration: 01:36:20.38, start: 0.000000, bitrate: 1886 kb/s
  Stream #0:0(tel): Video: h264 (Main), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
    Metadata:
      title           : www.HTPMovies.art
      BPS             : 1627282
      DURATION        : 01:36:20.084000000
      NUMBER_OF_FRAMES: 138722
      NUMBER_OF_BYTES : 1175728955
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-10-06 19:18:24
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(tel): Audio: eac3, 48000 Hz, 5.1(side), fltp, 192 kb/s (default)
    Metadata:
      title           : www.HTPMovies.art - [DD+ 5.1 - 192Kbps]
      BPS             : 192000
      DURATION        : 01:36:20.384000000
      NUMBER_OF_FRAMES: 180637
      NUMBER_OF_BYTES : 138729216
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-10-06 19:18:24
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(tel): Audio: aac (HE-AAC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : www.HTPMovies.art - [AAC 2.0 - 64Kbps]
      BPS             : 63999
      DURATION        : 01:36:20.182000000
      NUMBER_OF_FRAMES: 135473
      NUMBER_OF_BYTES : 46241450
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-10-06 19:18:24
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip (default)

**Comment by bipinkrish** [comment]
what can I understand from this, tell me sent file info, received file info

**Comment by satyamisme** [comment]
decoding for stream 10 failed
[matroska,webm @ 0x55f7d2a9e540] Could not find codec parameters for stream 10 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size    code not compatible for decoding

**Comment by bipinkrish** [comment]
Is this error for all files?

**Comment by satyamisme** [comment]
only for resolution 720p and above  x265 x264

**Comment by bipinkrish** [comment]
> only for resolution 720p and above x265 x264

From what format to what format are you converting

**Comment by satyamisme** [comment]
MKv to mp4

**Comment by satyamisme** [comment]
example 1  https://appdrive.info/file/bHISvsDryG1RB5ADGDYY
example 2 https://appdrive.info/file/XQMGQp91tb3ahY7lEyma

**Comment by satyamisme** [comment]
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
**

[mjpeg @ 0x55aac3381500] unable to decode APP fields: Invalid data found when processing input
    Last message repeated 9 times

**
[mjpeg @ 0x55aac3381500] No JPEG data found in image
**

> [matroska,webm @ 0x55aac3365540] decoding for stream 5 failed

**
**

> [matroska,webm @ 0x55aac3365540] Could not find codec parameters for stream 5 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size

**
**

> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> Input #0, matroska,webm, from

** '/usr/src/app/downloads/www_HTPMovies_art_Alluri_2022_720p_AHA_WEB_DL_x264_Telugu_DD+_5.mkv':
  Metadata:




highlighted error it might help

**Comment by bipinkrish** [comment]
> ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers built with gcc 11 (Ubuntu 11.2.0-19ubuntu1) configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared libavutil 56. 70.100 / 56. 70.100 libavcodec 58.134.100 / 58.134.100 libavformat 58. 76.100 / 58. 76.100 libavdevice 58. 13.100 / 58. 13.100 libavfilter 7.110.100 / 7.110.100 libswscale 5. 9.100 / 5. 9.100 libswresample 3. 9.100 / 3. 9.100 libpostproc 55. 9.100 / 55. 9.100 **
> 
> [mjpeg @ 0x55aac3381500] unable to decode APP fields: Invalid data found when processing input Last message repeated 9 times
> 
> ** [mjpeg @ 0x55aac3381500] No JPEG data found in image **
> 
> > [matroska,webm @ 0x55aac3365540] decoding for stream 5 failed
> 
> ** **
> 
> > [matroska,webm @ 0x55aac3365540] Could not find codec parameters for stream 5 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
> 
> ** **
> 
> > Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> > Input #0, matroska,webm, from
> 
> ** '/usr/src/app/downloads/www_HTPMovies_art_Alluri_2022_720p_AHA_WEB_DL_x264_Telugu_DD+_5.mkv': Metadata:
> 
> highlighted error it might help

have you tried it with my official bot?

**Comment by satyamisme** [comment]
tried every bot same Source File : Error in getting Info

Converted File : https://telegra.ph/www-HTPMovies-art-Alluri-2022-720p-AHA-WEB-DL-x265-Telugu-DD-5mp4-10-07-2

**Comment by satyamisme** [comment]
plaese include [https://pypi.org/project/ffmpy/0.0.4/]

**mpeg4 video** are output with no voice and enable **option send as document or media**

**Comment by bipinkrish** [comment]
> example 1 https://appdrive.info/file/bHISvsDryG1RB5ADGDYY example 2 https://appdrive.info/file/XQMGQp91tb3ahY7lEyma

I converted example 2 to mp4 and i don't see any problem, even audio is present
